storage:
 value: default
 wizard:
   name: "Storage Configuration"
   kind: cluster_storage

pytorch_version:
  value: "1.3.1"
  wizard:
    name: "PyTorch version"
    kind: select
    options:
    - "1.3.1"
    - "1.4.0"

tensorboard:
  value: false
  wizard:
    name: Install Tensorboard
    kind: boolean

src:
  value: https://github.com/kibernetika-ai/first-order-model
  wizard:
    name: "Source Code"
    kind: git

models:
 value: 'first-order-motion'
 version: '1.0.0'
 workspace: 'kuberlab-demo'
 wizard:
   name: "First Order Motion Model"
   kind: model

# Pip packages may be specified here in format that pip accepts.
packages:
  - "imageio-ffmpeg==0.4.1"
  - "tqdm==4.24.0"
  - "Pillow==5.2.0"